[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'tools\\update-dll-mingw'
	elseif dein#util#_is_cygwin()
		let cmd = 'make -f make_cygwin.mak'
		elseif executable('gmake')
		let cmd = 'gmake'
		else
		let cmd = 'make'
	endif
	let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'Valloric/MatchTagAlways'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'sonjapeterson/1989.vim'

[[plugins]]
repo = 'vim-scripts/chlordane.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

