# *****************************************
#
#      _/\/\____/\/\_/\/\__________________
#     _/\/\____/\/\________/\/\/\__/\/\___ 
#    _/\/\____/\/\_/\/\___/\/\/\/\/\/\/\_  
#   ___/\/\/\/\___/\/\___/\/\__/\__/\/\_   
#  _____/\/\_____/\/\/\_/\/\______/\/\_    
# ____________________________________     
#
# LAST UPDATE: 2018-09-06
#
# Install plugin lists for lasy load
#
# *****************************************

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo  = 'digitaltoad/vim-pug'
on_ft = ['pug']

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo  = 'wavded/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo  = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'MTDL9/vim-log-highlighting'
on_ft = ['log']

# [[plugins]]
# repo = 'sbdchd/neoformat'
# on_ft = ['javascript']

# [[plugins]]
# repo = 'prettier/vim-prettier'
# on_ft = ['javascript', 'vue']


