# *****************************************
#
#      _/\/\____/\/\_/\/\__________________
#     _/\/\____/\/\________/\/\/\__/\/\___ 
#    _/\/\____/\/\_/\/\___/\/\/\/\/\/\/\_  
#   ___/\/\/\/\___/\/\___/\/\__/\__/\/\_   
#  _____/\/\_____/\/\/\_/\/\______/\/\_    
# ____________________________________     
#
# LAST UPDATE: 2019-03-06
#
# Install plugin lists
#
# *****************************************

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'Valloric/MatchTagAlways'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/lightline.vim'

# color scheme
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'ajmwagar/vim-deus'

[[plugins]]
repo = 'kaicataldo/material.vim'

# dict
[[plugins]]
repo = 'miya0001/vim-dict-wordpress'



